function Deployments = importDeployments(workbookFile, sheetName, dataLines)
%IMPORTDEPLOYMENTS Import data from a spreadsheet
%  DEPLOYMENTS = IMPORTDEPLOYMENTS(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DEPLOYMENTS = IMPORTDEPLOYMENTS(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DEPLOYMENTS = IMPORTDEPLOYMENTS(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Deployments = importDeployments("F:\Project M2FED\Deployment_summary_9.29.19.xlsx", "Summary", [8, 27]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Dec-2020 11:26:12

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [8, 27];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["TotalofDeployments", "DeploymentID", "FamilyID", "DeploymentType", "Location", "NumberofParticipants", "PhoneIDs", "WatchIDs", "BeaconIDs", "StartDate", "EndDate", "DataLocation", "Comment", "Layout"];
opts.VariableTypes = ["double", "string", "double", "categorical", "categorical", "double", "string", "string", "string", "datetime", "datetime", "categorical", "string", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["DeploymentID", "PhoneIDs", "WatchIDs", "BeaconIDs", "Comment"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["DeploymentID", "DeploymentType", "Location", "PhoneIDs", "WatchIDs", "BeaconIDs", "DataLocation", "Comment", "Layout"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "StartDate", "InputFormat", "MM/dd/yyyy");
opts = setvaropts(opts, "EndDate", "InputFormat", "MM/dd/yyyy");

% Import the data
Deployments = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Deployments = [Deployments; tb]; %#ok<AGROW>
end

end